import { ApiError } from '../utils/http';
import { DbClient, query } from '../db/supabase';
import { env } from '../config/env';
export type RequestedLine={productId:string;variantId?:string|null;quantity:number};
export type PricedLine=RequestedLine&{productName:string;sku:string;variantName?:string|null;unitPrice:number;originalUnitPrice:number;offerDiscount:number;discount:number;lineTotal:number;categoryId:string;freeShipping:boolean;snapshot:Record<string,unknown>};
export type PriceResult={lines:PricedLine[];subtotal:number;discount:number;shipping:number;tax:number;total:number;coupon?:Record<string,unknown>};
const n=(x:any)=>Number(x??0);
const isKeralaState=(state:string|undefined)=>{const normalized=String(state??'').trim().toLowerCase().replace(/[._-]/g,' ');return normalized==='kerala'||normalized==='kl'||normalized.includes('kerala');};
export async function priceLines(lines:RequestedLine[],couponCode?:string,userId?:string,client?:DbClient,address?:{state?:string}|null):Promise<PriceResult>{
 if(!Array.isArray(lines)||!lines.length)throw new ApiError(400,'VALIDATION_ERROR','At least one item is required.');const keys=new Set<string>();for(const l of lines){if(!l.productId||!Number.isInteger(l.quantity)||l.quantity<1||l.quantity>99)throw new ApiError(400,'VALIDATION_ERROR','Each item needs a valid product and quantity.');const k=`${l.productId}:${l.variantId??''}`;if(keys.has(k))throw new ApiError(400,'DUPLICATE_ITEM','Duplicate cart items are not allowed.');keys.add(k);}
 const rows=(await query<any>(`select p.*,v.id variant_id,v.sku variant_sku,v.name variant_name,v.price variant_price,v.attributes variant_attributes,i.stock,i.reserved,i.id inventory_id from products p left join product_variants v on v.product_id=p.id and v.id=any($2::uuid[]) left join inventory i on i.variant_id=v.id or (i.product_id=p.id and i.variant_id is null) where p.id=any($1::uuid[]) and p.status='ACTIVE'`,[lines.map(x=>x.productId),lines.map(x=>x.variantId).filter(Boolean)],client)).rows;const map=new Map<string,any>();for(const r of rows)map.set(`${r.id}:${r.variant_id??''}`,r);const out:PricedLine[]=[];
 for(const l of lines){const r=map.get(`${l.productId}:${l.variantId??''}`)??map.get(`${l.productId}:`);if(!r||(l.variantId&&r.variant_id!==l.variantId))throw new ApiError(404,'PRODUCT_NOT_FOUND','One or more products or variants are unavailable.');if(n(r.stock)-n(r.reserved)<l.quantity)throw new ApiError(409,'OUT_OF_STOCK',`${r.name} is not available in the requested quantity.`);const price=n(r.variant_price??r.price);out.push({...l,productName:r.name,sku:r.variant_sku??r.sku,variantName:r.variant_name,unitPrice:price,originalUnitPrice:n(r.compare_at_price??r.price),offerDiscount:0,discount:0,lineTotal:price*l.quantity,categoryId:r.category_id,freeShipping:Boolean(r.free_shipping),snapshot:{productName:r.name,sku:r.variant_sku??r.sku,variant:r.variant_name??null,variantAttributes:r.variant_attributes??null,price}});}
 const subtotal=out.reduce((s,l)=>s+l.lineTotal,0);let discount=0;let coupon:Record<string,unknown>|undefined;
 if(couponCode){const c=(await query<any>("select * from coupons where code=upper($1) and status='ACTIVE' and start_at<=now() and end_at>=now()",[couponCode],client)).rows[0];if(!c)throw new ApiError(400,'INVALID_COUPON','Invalid or expired coupon code.');if(subtotal<n(c.minimum_order))throw new ApiError(400,'COUPON_NOT_APPLICABLE','This coupon does not meet the minimum order value.');if(c.usage_limit!=null&&n(c.usage_count)>=n(c.usage_limit))throw new ApiError(400,'COUPON_EXHAUSTED','This coupon has reached its usage limit.');if(userId&&c.per_customer_limit!=null){const used=n((await query<any>('select count(*) count from coupon_usages where coupon_id=$1 and user_id=$2',[c.id,userId],client)).rows[0].count);if(used>=n(c.per_customer_limit))throw new ApiError(400,'COUPON_LIMIT_REACHED','You have already used this coupon the maximum number of times.');}const products=(await query<any>('select product_id from coupon_products where coupon_id=$1',[c.id],client)).rows.map(x=>x.product_id);const cats=(await query<any>('select category_id from coupon_categories where coupon_id=$1',[c.id],client)).rows.map(x=>x.category_id);if((products.length||cats.length)&&!out.some(l=>products.includes(l.productId)||cats.includes(l.categoryId)))throw new ApiError(400,'COUPON_NOT_APPLICABLE','This coupon does not apply to these products.');discount=c.discount_type==='PERCENTAGE'?Math.floor(subtotal*n(c.discount_value)/100):n(c.discount_value);if(c.maximum_discount!=null)discount=Math.min(discount,n(c.maximum_discount));discount=Math.min(discount,subtotal);let rem=discount;out.forEach((l,i)=>{const share=i===out.length-1?rem:Math.floor(discount*l.lineTotal/subtotal);l.discount=share;l.lineTotal-=share;rem-=share;});coupon={id:c.id,code:c.code,discountType:c.discount_type,discountValue:c.discount_value,discount};}
 const hasChargeableItem=out.some(line=>!line.freeShipping);const shipping=hasChargeableItem?(isKeralaState(address?.state)?n(env.SHIPPING_KERALA_RATE):n(env.SHIPPING_OUTSIDE_KERALA_RATE)):0;const tax=Math.round((subtotal-discount)*n(env.TAX_RATE)/100);return{lines:out,subtotal,discount,shipping,tax,total:Math.max(0,subtotal-discount+shipping+tax),coupon};
}
