import { Router } from 'express';
import { query } from '../db/supabase';
import { ApiError, asyncHandler, ok } from '../utils/http';
const router=Router();
export const productShape=(r:any)=>({id:r.id,slug:r.slug,name:r.name,description:r.description,shortDescription:r.short_description,category:r.category_name,categoryId:r.category_id,collection:r.collection_name,collectionId:r.collection_id,sku:r.sku,sellingPrice:Number(r.price),originalPrice:Number(r.compare_at_price??r.price),discountPercent:r.compare_at_price?Math.round((1-Number(r.price)/Number(r.compare_at_price))*100):0,isSale:Number(r.compare_at_price??0)>Number(r.price),currency:r.currency,stock:Number(r.stock??0),lowStockThreshold:Number(r.low_stock_threshold??0),freeShipping:Boolean(r.free_shipping),images:r.images??[],coverImage:(r.images??[]).find((x:any)=>x.isCover)?.url??r.images?.[0]?.url,status:String(r.status).toLowerCase(),featured:r.featured,newArrival:r.new_arrival,material:r.material,fabric:r.fabric,fit:r.fit,care:r.care,seoTitle:r.seo_title,seoDescription:r.seo_description,tags:r.tags??[],attributes:r.attributes??{},rating:Number(r.rating??0),reviewsCount:Number(r.reviews_count??0),variants:r.variants??[]});
const joins=`from products p left join categories c on c.id=p.category_id left join collections co on co.id=p.collection_id left join lateral (select coalesce(json_agg(json_build_object('id',pi.id,'url',pi.url,'storageKey',pi.storage_key,'altText',pi.alt_text,'sortOrder',pi.sort_order,'isCover',pi.is_cover) order by pi.sort_order),'[]'::json) images from product_images pi where pi.product_id=p.id) im on true left join lateral (select coalesce(json_agg(json_build_object('id',v.id,'sku',v.sku,'name',v.name,'attributes',v.attributes,'price',v.price,'stock',i.stock,'reserved',i.reserved) order by v.created_at),'[]'::json) variants from product_variants v left join inventory i on i.variant_id=v.id where v.product_id=p.id and v.status=true) va on true left join lateral (select i.stock,i.reserved,i.low_stock_threshold from inventory i where i.product_id=p.id and i.variant_id is null limit 1) inv on true`;
async function list(req:any,res:any){const page=Math.max(1,Number(req.query.page??1)),limit=Math.min(100,Math.max(1,Number(req.query.limit??24)));const vals:any[]=[];const where=[`p.status='ACTIVE'`];const add=(v:any)=>{vals.push(v);return`$${vals.length}`;};if(req.query.category){const x=add(String(req.query.category));where.push(`(c.slug=${x} or c.id::text=${x})`);}if(req.query.collection){const x=add(String(req.query.collection));where.push(`(co.slug=${x} or co.id::text=${x})`);}if(req.query.search||req.query.q){const x=add(`%${String(req.query.search??req.query.q).toLowerCase()}%`);where.push(`(lower(p.name) like ${x} or lower(p.sku) like ${x} or exists(select 1 from unnest(p.tags) t where lower(t) like ${x}))`);}if(req.query.featured==='true')where.push('p.featured=true');if(req.query.newArrival==='true')where.push('p.new_arrival=true');if(req.query.minPrice)where.push(`p.price>=${add(Number(req.query.minPrice))}`);if(req.query.maxPrice)where.push(`p.price<=${add(Number(req.query.maxPrice))}`);if(req.query.inStock==='true'||req.query.availability==='in-stock')where.push('coalesce(inv.stock,0)-coalesce(inv.reserved,0)>0');const orders:any={price_asc:'p.price asc',price_desc:'p.price desc',newest:'p.created_at desc',rating:'p.rating desc',name:'p.name asc'};const offset=add((page-1)*limit),take=add(limit);const rows=(await query<any>(`select p.*,c.name category_name,co.name collection_name,im.images,va.variants,inv.stock,inv.low_stock_threshold,count(*) over() total ${joins} where ${where.join(' and ')} order by ${orders[String(req.query.sort??'newest')]??orders.newest} offset ${offset} limit ${take}`,vals)).rows;const total=Number(rows[0]?.total??0);ok(res,rows.map(productShape),{page,limit,total,totalPages:Math.ceil(total/limit)});}
router.get('/products',asyncHandler(list));
router.get('/products/:slug',asyncHandler(async(req,res)=>{const r=(await query<any>(`select p.*,c.name category_name,co.name collection_name,im.images,va.variants,inv.stock,inv.low_stock_threshold ${joins} where p.status='ACTIVE' and (p.slug=$1 or p.id::text=$1)`,[req.params.slug])).rows[0];if(!r)throw new ApiError(404,'PRODUCT_NOT_FOUND','Product not found.');ok(res,productShape(r));}));
router.get('/search',asyncHandler(async(req,res)=>{req.query.q=req.query.q??req.query.search;return list(req,res);}));
router.get('/categories',asyncHandler(async(_req,res)=>ok(res,(await query('select * from categories where status=true order by name')).rows)));
router.get('/collections',asyncHandler(async(_req,res)=>ok(res,(await query('select * from collections where status=true order by name')).rows)));
router.get('/offers',asyncHandler(async(req,res)=>{const where=req.query.activeOnly==='false'?'':'where status=true and start_at<=now() and end_at>=now()';ok(res,(await query(`select * from offers ${where} order by start_at desc`)).rows);}));
router.get('/coupons/active',asyncHandler(async(_req,res)=>ok(res,(await query("select id,code,discount_type,discount_value,minimum_order,maximum_discount,start_at,end_at from coupons where status='ACTIVE' and start_at<=now() and end_at>=now() and (usage_limit is null or usage_count<usage_limit) order by created_at desc")).rows)));
router.post('/offers/validate',asyncHandler(async(req,res)=>{const code=String(req.body?.code??'').trim().toUpperCase();const c=(await query("select * from coupons where code=$1 and status='ACTIVE' and start_at<=now() and end_at>=now()",[code])).rows[0];if(!c)throw new ApiError(400,'INVALID_COUPON','Invalid or expired coupon code.');ok(res,{valid:true,code:c.code,discountType:c.discount_type,discountValue:Number(c.discount_value),minimumOrder:Number(c.minimum_order),maximumDiscount:c.maximum_discount==null?null:Number(c.maximum_discount)});}));
export default router;
